FROM alpine/git as clone

WORKDIR /app
RUN git config --global http.version HTTP/1.1
RUN git clone https://github.com/SAMA-Communications/sama-client.git . --depth 1

FROM node:18.16.0 as builder

WORKDIR /app

COPY --from=clone /app .

RUN npm install

FROM node:18-slim

WORKDIR /app

COPY --from=builder /app /app

CMD ["npm", "run", "start"]