export const CONSTANTS = {
  LIMIT_MAX: 100,
  LAST_ACTIVITY_STATUS: {
    ONLINE: "online",
    OFFLINE: "offline",
  },
  SESSION_NODE_KEY: "NODE_ENDPOINT",
  SESSION_INACTIVE_STATE_KEY: "MOBILE_INACTIVE",
  HTTP_DEVICE_ID: "HTTP_CLIENT",
  HTTP_ADMIN_API_KEY_HEADER: "admin-api-key",
}
