export const CONSTANTS = {
  LIMIT_MAX: process.env.CONVERSATION_PRELOAD_COUNT,
  LAST_ACTIVITY_STATUS: {
    ONLINE: "online",
    OFFLINE: "offline",
  },
  SESSION_NODE_KEY: "NODE_ENDPOINT",
  SESSION_INACTIVE_STATE_KEY: "MOBILE_INACTIVE",
}
