export const CONSTANTS = {
  CONVERSATION_LIMIT_MAX: +process.env.CONVERSATION_PRELOAD_COUNT,
  MESSGAE_LIMIT_MAX: +process.env.MESSGAE_LIMIT_MAX,
  SEARCH_LIMIT_MAX: +process.env.SEARCH_LIMIT_MAX,
  LAST_ACTIVITY_STATUS: {
    ONLINE: "online",
    OFFLINE: "offline",
  },
  SESSION_NODE_KEY: "NODE_ENDPOINT",
  SESSION_INACTIVE_STATE_KEY: "MOBILE_INACTIVE",
  HTTP_DEVICE_ID: "HTTP_CLIENT",
  HTTP_ADMIN_API_KEY_HEADER: "admin-api-key",
}
