version: "3.8"

services:
  sama-server:
    build:
      context: ../../../.
      dockerfile: Dockerfile
    container_name: "sama-server"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - S3_ENDPOINT=${S3_ENDPOINT:-http://172.25.0.2:9000}
    networks:
      sama_network:
        ipv4_address: 172.25.0.7
    volumes:
      - ../../../.env.docker:/app/.env
    ports:
      - "9000:9001"
