version: "3.8"

services:
  mongo:
    platform: linux/x86_64
    image: mongo:6.0
    networks:
      sama_network:
        ipv4_address: 172.25.0.4
    container_name: server_mongo_database
    restart: always
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_DATABASE=samadb
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/samadb --quiet
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis
    networks:
      sama_network:
        ipv4_address: 172.25.0.5
    container_name: server_redis_database
    restart: always
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    networks:
      sama_network:
        ipv4_address: 172.25.0.6
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
