version: "3.8"

services:
  s3:
    image: minio/minio
    networks:
      sama_network:
        ipv4_address: 172.25.0.2
    ports:
      - "9011:9001"
      - "9010:9000"
    volumes:
      - data:/data
    env_file:
      - ../../../.env.docker
    command: server --address 0.0.0.0:9000 --console-address :9001 /data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3

  s3-service:
    image: minio/mc
    networks:
      sama_network:
        ipv4_address: 172.25.0.3
    depends_on:
      s3:
        condition: service_healthy
    env_file:
      - ../../../.env.docker
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set sama http://s3:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb sama/samabucket;
      /usr/bin/mc policy set public sama/samabucket;
      /usr/bin/mc admin user svcacct add --access-key $${MINIO_ACCESS_KEY} --secret-key $${MINIO_SECRET_KEY} sama $${MINIO_ROOT_USER}
      "