version: "3.8"

services:
  s3:
    image: dxflrs/garage:v2.4.1
    networks:
      sama_network:
        ipv4_address: 172.25.0.2
    ports:
      - "9011:3903"
      - "9010:9000"
    volumes:
      - data:/var/lib/garage
      - ../../garage/garage.toml:/etc/garage.toml:ro
    env_file:
      - ../../../.env.docker
    healthcheck:
      test: ["CMD", "/garage", "status"]
      interval: 30s
      timeout: 20s
      retries: 3

  s3-service:
    image: curlimages/curl
    networks:
      sama_network:
        ipv4_address: 172.25.0.3
    depends_on:
      s3:
        condition: service_healthy
    env_file:
      - ../../../.env.docker
    volumes:
      - ../../garage/init.sh:/init.sh:ro
    entrypoint: ["/bin/sh", "/init.sh"]
