FROM alpine/git as clone

WORKDIR /app

RUN git clone https://github.com/SAMA-Communications/sama-server-dashboard.git .

FROM node:22.14.0 as builder

WORKDIR /app

COPY --from=clone /app .

RUN npm install

FROM node:22-slim

WORKDIR /app

COPY --from=builder /app /app

CMD ["npm", "run", "start"]